version: '3'
services: 
    client:
        build: 
            context: .
        environment:
            CHOKIDAR_USEPOLLING: "true"
        command: npm start
        container_name: client
        ports:
            - "3000:3000"        
        volumes: 
            - ./:/app
            - /app/node_modules